spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: root

logging:
  level:
    root: warn
    com.ljh.mp.dao: trace
  pattern:
    console: '%p%m%n'

mybatis-plus:
  # MyBatis Mapper 所对应的 XML 文件位置
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      # 主键全局策略
      id-type: assign_uuid
      # 字段验证策略
      select-strategy: default
      insert-strategy: default
      update-strategy: default
      # 表名前缀
      # table-prefix: mp_
  # MyBatis 配置文件位置
  # config-location: classpath:mybatis-config.xml
  # MyBaits 别名包扫描路径
  typeAliasesPackage: com.ljh.mp.entity
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，默认为true，不能和 config-location 同时出现
    mapUnderscoreToCamelCase: true