spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: root
    password: test
  sql:
    init:
      schema-locations: classpath:sql/association/schema-h2.sql
      data-locations: classpath:sql/association/data-h2.sql
