server:
  port: 6011

spring:
  profiles:
    active: association

logging:
  level:
    root: warn
    # com.ljh.mp.dao: trace
    com.ljh.mp.dao: info
  pattern:
    console: '%p%m%n'

mybatis-plus:
  # MyBatis Mapper 所对应的 XML 文件位置
  mapper-locations: /classpath*:mapper/**/*.xml
  # MyBaits 别名包扫描路径
  type-aliases-package: com.ljh.mp.entity
  global-config:
    db-config:
      property-format: "\"%s\""