spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test
  sql:
    init:
      schema-locations: classpath:sql/associtaion/schema-h2.sql
      data-locations: classpath:sql/associtaion/data-h2.sql