server:
  port: 6011

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test
  sql:
    init:
      schema-locations: classpath:sql/schema-h2.sql
      data-locations: classpath:sql/data-h2.sql
  jackson:
    serialization:
      indent-output: true

mybatis:
  type-aliases-package: com.ljh.entity
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: h2
  reasonable: true
  support-methods-arguments: true