spring:
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    # url: jdbc:mysql://localhost:3306/mp_advance?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    url: jdbc:p6spy:mysql://localhost:3306/mp_advance?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root

logging:
  level:
    root: warn
    com.ljh.mp.dao: trace
  pattern:
    console: '%p%m%n'

mybatis-plus:
  global-config:
    db-config:
      # 逻辑未删除值
      logic-not-delete-value: 0
      # 逻辑已删除值
      logic-delete-value: 1
  configuration:
    # 枚举处理类
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  # 枚举类扫描路径；支持统配符 * 或者 ; 分割
  type-enums-package: com.ljh.mp.enums